-- 1. Create the staff_profile table
CREATE TABLE public.staff_profile (
  id bigint generated by default as identity not null,
  name text not null,
  email text not null,
  phone text not null,
  specialty text null,                           -- e.g., 'Hair Coloring Specialist', 'Nail Artist'
  avatar_url text null,
  is_available boolean not null default true,     -- To easily hide/show staff on frontend
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone null,

  constraint staff_profile_pkey primary key (id),
  constraint staff_profile_email_key unique (email)
) TABLESPACE pg_default;

-- 2. Create the salon appointment table with BOTH User and Staff relationships
CREATE TABLE public.appointment (
  id bigint generated by default as identity not null,
  user_id bigint not null,                      -- Links to the Customer (user_profile)
  staff_id bigint not null,                     -- Links to the Stylist (staff_profile)
  service_name text not null,                   -- e.g., 'Haircut', 'Manicure'
  appointment_date date not null,
  appointment_time time without time zone not null,
  price numeric(10, 2) not null,
  duration_minutes integer not null default 30,
  status text not null default 'pending',       -- 'pending', 'confirmed', 'completed', 'cancelled'
  notes text null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone null,

  constraint appointment_pkey primary key (id),

  -- Relationship 1: Connects to your user_profile table
  constraint fk_appointment_user 
    foreign key (user_id) 
    references public.user_profile (id)
    on delete cascade,

  -- Relationship 2: Connects to your new staff_profile table
  constraint fk_appointment_staff 
    foreign key (staff_id) 
    references public.staff_profile (id)
    on delete restrict                          -- 'restrict' prevents deleting a staff member if they have active appointments
) TABLESPACE pg_default;

-- 3. Enable Row Level Security (RLS)
ALTER TABLE public.staff_profile ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.appointment ENABLE ROW LEVEL SECURITY;

-- 4. Create RLS Policies
-- Allow anyone (even anonymous visitors browsing your Vite site) to see who works at the salon
CREATE POLICY "Allow public read access to staff" 
ON public.staff_profile FOR SELECT 
TO public 
USING (true);

-- Allow authenticated users to view only their own appointments
CREATE POLICY "Users can view their own appointments" 
ON public.appointment FOR SELECT 
TO authenticated 
USING (user_id = (SELECT id FROM public.user_profile WHERE id = user_id));